services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: mini-collection-backend
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      JWT_SECRET: supersecret
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: mini-collection-frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:4000
      NEXT_PUBLIC_WS_URL: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pgdata:
